Remove DHCP Column from Output
Not every logical switch contains DHCP IP Pool information. Removing
the DHCP column from being output.

Resolving the Following Error:
(VMWonAWSDemo) kruddy-m02:vsphere-automation-sdk-python kyleruddy$
python3 ./samples/vmc/networks/logical_network_crud.py -r $refreshtoken
-o $orgid -s $sddcid --network-name 'Python-SDK-LogicalNetwork' -c

# Example: Add a logical network to the compute gateway
  Compute Gateway ID: edge-2

# New logical network "Python-SDK-LogicalNetwork" is added

# Example: List all logical networks
Traceback (most recent call last):
  File "./samples/vmc/networks/logical_network_crud.py", line 208, in
<module>
    main()
  File "./samples/vmc/networks/logical_network_crud.py", line 201, in
main
    logical_network_crud.get_logical_network()
  File "./samples/vmc/networks/logical_network_crud.py", line 134, in
get_logical_network
    self.print_output(networks)
  File "./samples/vmc/networks/logical_network_crud.py", line 192, in
print_output
    network.dhcp_configs.ip_pools[0].ip_range])
AttributeError: 'NoneType' object has no attribute 'ip_pools'